<?php
/**
 * ConversationWebchatContext
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ultracart\v2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ultracart\v2\models;

use \ArrayAccess;
use \ultracart\v2\ObjectSerializer;

/**
 * ConversationWebchatContext Class Doc Comment
 *
 * @category Class
 * @package  ultracart\v2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ConversationWebchatContext implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ConversationWebchatContext';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'auto_orders' => '\ultracart\v2\models\AutoOrder[]',
        'cart' => '\ultracart\v2\models\Cart',
        'current_url' => 'string',
        'orders' => '\ultracart\v2\models\Order[]',
        'page_view' => '\ultracart\v2\models\HitPageView[]',
        'session_start' => '\ultracart\v2\models\HitSessionStart',
        'session_utm' => '\ultracart\v2\models\HitSessionUtm'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'auto_orders' => null,
        'cart' => null,
        'current_url' => null,
        'orders' => null,
        'page_view' => null,
        'session_start' => null,
        'session_utm' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'auto_orders' => 'auto_orders',
        'cart' => 'cart',
        'current_url' => 'current_url',
        'orders' => 'orders',
        'page_view' => 'page_view',
        'session_start' => 'session_start',
        'session_utm' => 'session_utm'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'auto_orders' => 'setAutoOrders',
        'cart' => 'setCart',
        'current_url' => 'setCurrentUrl',
        'orders' => 'setOrders',
        'page_view' => 'setPageView',
        'session_start' => 'setSessionStart',
        'session_utm' => 'setSessionUtm'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'auto_orders' => 'getAutoOrders',
        'cart' => 'getCart',
        'current_url' => 'getCurrentUrl',
        'orders' => 'getOrders',
        'page_view' => 'getPageView',
        'session_start' => 'getSessionStart',
        'session_utm' => 'getSessionUtm'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['auto_orders'] = $data['auto_orders'] ?? null;
        $this->container['cart'] = $data['cart'] ?? null;
        $this->container['current_url'] = $data['current_url'] ?? null;
        $this->container['orders'] = $data['orders'] ?? null;
        $this->container['page_view'] = $data['page_view'] ?? null;
        $this->container['session_start'] = $data['session_start'] ?? null;
        $this->container['session_utm'] = $data['session_utm'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets auto_orders
     *
     * @return \ultracart\v2\models\AutoOrder[]|null
     */
    public function getAutoOrders()
    {
        return $this->container['auto_orders'];
    }

    /**
     * Sets auto_orders
     *
     * @param \ultracart\v2\models\AutoOrder[]|null $auto_orders auto_orders
     *
     * @return self
     */
    public function setAutoOrders($auto_orders)
    {
        $this->container['auto_orders'] = $auto_orders;

        return $this;
    }

    /**
     * Gets cart
     *
     * @return \ultracart\v2\models\Cart|null
     */
    public function getCart()
    {
        return $this->container['cart'];
    }

    /**
     * Sets cart
     *
     * @param \ultracart\v2\models\Cart|null $cart cart
     *
     * @return self
     */
    public function setCart($cart)
    {
        $this->container['cart'] = $cart;

        return $this;
    }

    /**
     * Gets current_url
     *
     * @return string|null
     */
    public function getCurrentUrl()
    {
        return $this->container['current_url'];
    }

    /**
     * Sets current_url
     *
     * @param string|null $current_url current_url
     *
     * @return self
     */
    public function setCurrentUrl($current_url)
    {
        $this->container['current_url'] = $current_url;

        return $this;
    }

    /**
     * Gets orders
     *
     * @return \ultracart\v2\models\Order[]|null
     */
    public function getOrders()
    {
        return $this->container['orders'];
    }

    /**
     * Sets orders
     *
     * @param \ultracart\v2\models\Order[]|null $orders orders
     *
     * @return self
     */
    public function setOrders($orders)
    {
        $this->container['orders'] = $orders;

        return $this;
    }

    /**
     * Gets page_view
     *
     * @return \ultracart\v2\models\HitPageView[]|null
     */
    public function getPageView()
    {
        return $this->container['page_view'];
    }

    /**
     * Sets page_view
     *
     * @param \ultracart\v2\models\HitPageView[]|null $page_view page_view
     *
     * @return self
     */
    public function setPageView($page_view)
    {
        $this->container['page_view'] = $page_view;

        return $this;
    }

    /**
     * Gets session_start
     *
     * @return \ultracart\v2\models\HitSessionStart|null
     */
    public function getSessionStart()
    {
        return $this->container['session_start'];
    }

    /**
     * Sets session_start
     *
     * @param \ultracart\v2\models\HitSessionStart|null $session_start session_start
     *
     * @return self
     */
    public function setSessionStart($session_start)
    {
        $this->container['session_start'] = $session_start;

        return $this;
    }

    /**
     * Gets session_utm
     *
     * @return \ultracart\v2\models\HitSessionUtm|null
     */
    public function getSessionUtm()
    {
        return $this->container['session_utm'];
    }

    /**
     * Sets session_utm
     *
     * @param \ultracart\v2\models\HitSessionUtm|null $session_utm session_utm
     *
     * @return self
     */
    public function setSessionUtm($session_utm)
    {
        $this->container['session_utm'] = $session_utm;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


