<?php
/**
 * PaymentsConfigurationEcheck
 *
 * PHP version 5
 *
 * @category Class
 * @package  ultracart\v2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ultracart\v2\models;

use \ArrayAccess;
use \ultracart\v2\ObjectSerializer;

/**
 * PaymentsConfigurationEcheck Class Doc Comment
 *
 * @category Class
 * @package  ultracart\v2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PaymentsConfigurationEcheck implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PaymentsConfigurationEcheck';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'accept_e_check' => 'bool',
        'e_check_accounting_code' => 'string',
        'e_check_deposit_to_account' => 'string',
        'restrictions' => '\ultracart\v2\models\PaymentsConfigurationRestrictions'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'accept_e_check' => null,
        'e_check_accounting_code' => null,
        'e_check_deposit_to_account' => null,
        'restrictions' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'accept_e_check' => 'acceptECheck',
        'e_check_accounting_code' => 'eCheckAccountingCode',
        'e_check_deposit_to_account' => 'eCheckDepositToAccount',
        'restrictions' => 'restrictions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'accept_e_check' => 'setAcceptECheck',
        'e_check_accounting_code' => 'setECheckAccountingCode',
        'e_check_deposit_to_account' => 'setECheckDepositToAccount',
        'restrictions' => 'setRestrictions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'accept_e_check' => 'getAcceptECheck',
        'e_check_accounting_code' => 'getECheckAccountingCode',
        'e_check_deposit_to_account' => 'getECheckDepositToAccount',
        'restrictions' => 'getRestrictions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['accept_e_check'] = isset($data['accept_e_check']) ? $data['accept_e_check'] : null;
        $this->container['e_check_accounting_code'] = isset($data['e_check_accounting_code']) ? $data['e_check_accounting_code'] : null;
        $this->container['e_check_deposit_to_account'] = isset($data['e_check_deposit_to_account']) ? $data['e_check_deposit_to_account'] : null;
        $this->container['restrictions'] = isset($data['restrictions']) ? $data['restrictions'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets accept_e_check
     *
     * @return bool
     */
    public function getAcceptECheck()
    {
        return $this->container['accept_e_check'];
    }

    /**
     * Sets accept_e_check
     *
     * @param bool $accept_e_check accept_e_check
     *
     * @return $this
     */
    public function setAcceptECheck($accept_e_check)
    {
        $this->container['accept_e_check'] = $accept_e_check;

        return $this;
    }

    /**
     * Gets e_check_accounting_code
     *
     * @return string
     */
    public function getECheckAccountingCode()
    {
        return $this->container['e_check_accounting_code'];
    }

    /**
     * Sets e_check_accounting_code
     *
     * @param string $e_check_accounting_code e_check_accounting_code
     *
     * @return $this
     */
    public function setECheckAccountingCode($e_check_accounting_code)
    {
        $this->container['e_check_accounting_code'] = $e_check_accounting_code;

        return $this;
    }

    /**
     * Gets e_check_deposit_to_account
     *
     * @return string
     */
    public function getECheckDepositToAccount()
    {
        return $this->container['e_check_deposit_to_account'];
    }

    /**
     * Sets e_check_deposit_to_account
     *
     * @param string $e_check_deposit_to_account e_check_deposit_to_account
     *
     * @return $this
     */
    public function setECheckDepositToAccount($e_check_deposit_to_account)
    {
        $this->container['e_check_deposit_to_account'] = $e_check_deposit_to_account;

        return $this;
    }

    /**
     * Gets restrictions
     *
     * @return \ultracart\v2\models\PaymentsConfigurationRestrictions
     */
    public function getRestrictions()
    {
        return $this->container['restrictions'];
    }

    /**
     * Sets restrictions
     *
     * @param \ultracart\v2\models\PaymentsConfigurationRestrictions $restrictions restrictions
     *
     * @return $this
     */
    public function setRestrictions($restrictions)
    {
        $this->container['restrictions'] = $restrictions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


