<?php
/**
 * SfvbUpsellStepOffer
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ultracart\v2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ultracart\v2\models;

use \ArrayAccess;
use \ultracart\v2\ObjectSerializer;

/**
 * SfvbUpsellStepOffer Class Doc Comment
 *
 * @category Class
 * @package  ultracart\v2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SfvbUpsellStepOffer implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SfvbUpsellStepOffer';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'downsell_offer_active' => 'bool',
        'downsell_offer_name' => 'string',
        'downsell_offer_oid' => 'int',
        'downsell_offer_stats' => '\ultracart\v2\models\SfvbUpsellStats',
        'offer_active' => 'bool',
        'offer_name' => 'string',
        'offer_oid' => 'int',
        'offer_stats' => '\ultracart\v2\models\SfvbUpsellStats'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'downsell_offer_active' => null,
        'downsell_offer_name' => null,
        'downsell_offer_oid' => 'int32',
        'downsell_offer_stats' => null,
        'offer_active' => null,
        'offer_name' => null,
        'offer_oid' => 'int32',
        'offer_stats' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'downsell_offer_active' => 'downsell_offer_active',
        'downsell_offer_name' => 'downsell_offer_name',
        'downsell_offer_oid' => 'downsell_offer_oid',
        'downsell_offer_stats' => 'downsell_offer_stats',
        'offer_active' => 'offer_active',
        'offer_name' => 'offer_name',
        'offer_oid' => 'offer_oid',
        'offer_stats' => 'offer_stats'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'downsell_offer_active' => 'setDownsellOfferActive',
        'downsell_offer_name' => 'setDownsellOfferName',
        'downsell_offer_oid' => 'setDownsellOfferOid',
        'downsell_offer_stats' => 'setDownsellOfferStats',
        'offer_active' => 'setOfferActive',
        'offer_name' => 'setOfferName',
        'offer_oid' => 'setOfferOid',
        'offer_stats' => 'setOfferStats'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'downsell_offer_active' => 'getDownsellOfferActive',
        'downsell_offer_name' => 'getDownsellOfferName',
        'downsell_offer_oid' => 'getDownsellOfferOid',
        'downsell_offer_stats' => 'getDownsellOfferStats',
        'offer_active' => 'getOfferActive',
        'offer_name' => 'getOfferName',
        'offer_oid' => 'getOfferOid',
        'offer_stats' => 'getOfferStats'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['downsell_offer_active'] = $data['downsell_offer_active'] ?? null;
        $this->container['downsell_offer_name'] = $data['downsell_offer_name'] ?? null;
        $this->container['downsell_offer_oid'] = $data['downsell_offer_oid'] ?? null;
        $this->container['downsell_offer_stats'] = $data['downsell_offer_stats'] ?? null;
        $this->container['offer_active'] = $data['offer_active'] ?? null;
        $this->container['offer_name'] = $data['offer_name'] ?? null;
        $this->container['offer_oid'] = $data['offer_oid'] ?? null;
        $this->container['offer_stats'] = $data['offer_stats'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets downsell_offer_active
     *
     * @return bool|null
     */
    public function getDownsellOfferActive()
    {
        return $this->container['downsell_offer_active'];
    }

    /**
     * Sets downsell_offer_active
     *
     * @param bool|null $downsell_offer_active Read only.  Whether the downsell offer is switched on.
     *
     * @return self
     */
    public function setDownsellOfferActive($downsell_offer_active)
    {
        $this->container['downsell_offer_active'] = $downsell_offer_active;

        return $this;
    }

    /**
     * Gets downsell_offer_name
     *
     * @return string|null
     */
    public function getDownsellOfferName()
    {
        return $this->container['downsell_offer_name'];
    }

    /**
     * Sets downsell_offer_name
     *
     * @param string|null $downsell_offer_name Read only.  The downsell offer's name.
     *
     * @return self
     */
    public function setDownsellOfferName($downsell_offer_name)
    {
        $this->container['downsell_offer_name'] = $downsell_offer_name;

        return $this;
    }

    /**
     * Gets downsell_offer_oid
     *
     * @return int|null
     */
    public function getDownsellOfferOid()
    {
        return $this->container['downsell_offer_oid'];
    }

    /**
     * Sets downsell_offer_oid
     *
     * @param int|null $downsell_offer_oid The offer shown when the shopper declines offer_oid.  Omitted or null for no downsell.  Must be an offer of this storefront.
     *
     * @return self
     */
    public function setDownsellOfferOid($downsell_offer_oid)
    {
        $this->container['downsell_offer_oid'] = $downsell_offer_oid;

        return $this;
    }

    /**
     * Gets downsell_offer_stats
     *
     * @return \ultracart\v2\models\SfvbUpsellStats|null
     */
    public function getDownsellOfferStats()
    {
        return $this->container['downsell_offer_stats'];
    }

    /**
     * Sets downsell_offer_stats
     *
     * @param \ultracart\v2\models\SfvbUpsellStats|null $downsell_offer_stats downsell_offer_stats
     *
     * @return self
     */
    public function setDownsellOfferStats($downsell_offer_stats)
    {
        $this->container['downsell_offer_stats'] = $downsell_offer_stats;

        return $this;
    }

    /**
     * Gets offer_active
     *
     * @return bool|null
     */
    public function getOfferActive()
    {
        return $this->container['offer_active'];
    }

    /**
     * Sets offer_active
     *
     * @param bool|null $offer_active Read only.  Whether the offer is switched on.
     *
     * @return self
     */
    public function setOfferActive($offer_active)
    {
        $this->container['offer_active'] = $offer_active;

        return $this;
    }

    /**
     * Gets offer_name
     *
     * @return string|null
     */
    public function getOfferName()
    {
        return $this->container['offer_name'];
    }

    /**
     * Sets offer_name
     *
     * @param string|null $offer_name Read only.  The offer's name.
     *
     * @return self
     */
    public function setOfferName($offer_name)
    {
        $this->container['offer_name'] = $offer_name;

        return $this;
    }

    /**
     * Gets offer_oid
     *
     * @return int|null
     */
    public function getOfferOid()
    {
        return $this->container['offer_oid'];
    }

    /**
     * Sets offer_oid
     *
     * @param int|null $offer_oid The offer shown at this step.  Must be an offer of this storefront.
     *
     * @return self
     */
    public function setOfferOid($offer_oid)
    {
        $this->container['offer_oid'] = $offer_oid;

        return $this;
    }

    /**
     * Gets offer_stats
     *
     * @return \ultracart\v2\models\SfvbUpsellStats|null
     */
    public function getOfferStats()
    {
        return $this->container['offer_stats'];
    }

    /**
     * Sets offer_stats
     *
     * @param \ultracart\v2\models\SfvbUpsellStats|null $offer_stats offer_stats
     *
     * @return self
     */
    public function setOfferStats($offer_stats)
    {
        $this->container['offer_stats'] = $offer_stats;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


