<?php
/**
 * SfvbPreviewAccessResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ultracart\v2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ultracart\v2\models;

use \ArrayAccess;
use \ultracart\v2\ObjectSerializer;

/**
 * SfvbPreviewAccessResponse Class Doc Comment
 *
 * @category Class
 * @package  ultracart\v2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SfvbPreviewAccessResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SfvbPreviewAccessResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'access_url' => 'string',
        'expires_in_seconds' => 'int',
        'path' => 'string',
        'preview_session_id' => 'string',
        'session_lifetime_seconds' => 'int',
        'single_use' => 'bool',
        'theme_oid' => 'int',
        'usage_note' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'access_url' => null,
        'expires_in_seconds' => 'int32',
        'path' => null,
        'preview_session_id' => null,
        'session_lifetime_seconds' => 'int32',
        'single_use' => null,
        'theme_oid' => 'int32',
        'usage_note' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'access_url' => 'access_url',
        'expires_in_seconds' => 'expires_in_seconds',
        'path' => 'path',
        'preview_session_id' => 'preview_session_id',
        'session_lifetime_seconds' => 'session_lifetime_seconds',
        'single_use' => 'single_use',
        'theme_oid' => 'theme_oid',
        'usage_note' => 'usage_note'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'access_url' => 'setAccessUrl',
        'expires_in_seconds' => 'setExpiresInSeconds',
        'path' => 'setPath',
        'preview_session_id' => 'setPreviewSessionId',
        'session_lifetime_seconds' => 'setSessionLifetimeSeconds',
        'single_use' => 'setSingleUse',
        'theme_oid' => 'setThemeOid',
        'usage_note' => 'setUsageNote'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'access_url' => 'getAccessUrl',
        'expires_in_seconds' => 'getExpiresInSeconds',
        'path' => 'getPath',
        'preview_session_id' => 'getPreviewSessionId',
        'session_lifetime_seconds' => 'getSessionLifetimeSeconds',
        'single_use' => 'getSingleUse',
        'theme_oid' => 'getThemeOid',
        'usage_note' => 'getUsageNote'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['access_url'] = $data['access_url'] ?? null;
        $this->container['expires_in_seconds'] = $data['expires_in_seconds'] ?? null;
        $this->container['path'] = $data['path'] ?? null;
        $this->container['preview_session_id'] = $data['preview_session_id'] ?? null;
        $this->container['session_lifetime_seconds'] = $data['session_lifetime_seconds'] ?? null;
        $this->container['single_use'] = $data['single_use'] ?? null;
        $this->container['theme_oid'] = $data['theme_oid'] ?? null;
        $this->container['usage_note'] = $data['usage_note'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets access_url
     *
     * @return string|null
     */
    public function getAccessUrl()
    {
        return $this->container['access_url'];
    }

    /**
     * Sets access_url
     *
     * @param string|null $access_url One time link on the storefront's own host.  Opening it in any browser, including an agent's built in browser with no UltraCart login, gets past the storefront lock and applies the preview session and theme for the rest of that browser's session, then redirects to path.  It is a credential until used, so do not paste it anywhere other than the browser that should open it.
     *
     * @return self
     */
    public function setAccessUrl($access_url)
    {
        $this->container['access_url'] = $access_url;

        return $this;
    }

    /**
     * Gets expires_in_seconds
     *
     * @return int|null
     */
    public function getExpiresInSeconds()
    {
        return $this->container['expires_in_seconds'];
    }

    /**
     * Sets expires_in_seconds
     *
     * @param int|null $expires_in_seconds Seconds left to open access_url.  It stops working after that, and after its first use.
     *
     * @return self
     */
    public function setExpiresInSeconds($expires_in_seconds)
    {
        $this->container['expires_in_seconds'] = $expires_in_seconds;

        return $this;
    }

    /**
     * Gets path
     *
     * @return string|null
     */
    public function getPath()
    {
        return $this->container['path'];
    }

    /**
     * Sets path
     *
     * @param string|null $path Storefront path the browser lands on, after reserved preview parameters are removed.
     *
     * @return self
     */
    public function setPath($path)
    {
        $this->container['path'] = $path;

        return $this;
    }

    /**
     * Gets preview_session_id
     *
     * @return string|null
     */
    public function getPreviewSessionId()
    {
        return $this->container['preview_session_id'];
    }

    /**
     * Sets preview_session_id
     *
     * @param string|null $preview_session_id The preview session applied, when one was requested.
     *
     * @return self
     */
    public function setPreviewSessionId($preview_session_id)
    {
        $this->container['preview_session_id'] = $preview_session_id;

        return $this;
    }

    /**
     * Gets session_lifetime_seconds
     *
     * @return int|null
     */
    public function getSessionLifetimeSeconds()
    {
        return $this->container['session_lifetime_seconds'];
    }

    /**
     * Sets session_lifetime_seconds
     *
     * @param int|null $session_lifetime_seconds How long the browser stays in preview once access_url is opened.  The remaining life of the preview session, or eight hours when none was given.  The user and their storefront permission are checked again on every page, so removing either ends it sooner.
     *
     * @return self
     */
    public function setSessionLifetimeSeconds($session_lifetime_seconds)
    {
        $this->container['session_lifetime_seconds'] = $session_lifetime_seconds;

        return $this;
    }

    /**
     * Gets single_use
     *
     * @return bool|null
     */
    public function getSingleUse()
    {
        return $this->container['single_use'];
    }

    /**
     * Sets single_use
     *
     * @param bool|null $single_use Always true.  A second open of access_url returns 410.
     *
     * @return self
     */
    public function setSingleUse($single_use)
    {
        $this->container['single_use'] = $single_use;

        return $this;
    }

    /**
     * Gets theme_oid
     *
     * @return int|null
     */
    public function getThemeOid()
    {
        return $this->container['theme_oid'];
    }

    /**
     * Sets theme_oid
     *
     * @param int|null $theme_oid The theme shown, when one was requested.
     *
     * @return self
     */
    public function setThemeOid($theme_oid)
    {
        $this->container['theme_oid'] = $theme_oid;

        return $this;
    }

    /**
     * Gets usage_note
     *
     * @return string|null
     */
    public function getUsageNote()
    {
        return $this->container['usage_note'];
    }

    /**
     * Sets usage_note
     *
     * @param string|null $usage_note Plain language instructions, safe to show a user.
     *
     * @return self
     */
    public function setUsageNote($usage_note)
    {
        $this->container['usage_note'] = $usage_note;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


