<?php
/**
 * TaxCity
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ultracart\v2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ultracart\v2\models;

use \ArrayAccess;
use \ultracart\v2\ObjectSerializer;

/**
 * TaxCity Class Doc Comment
 *
 * @category Class
 * @package  ultracart\v2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TaxCity implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TaxCity';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'accounting_code' => 'string',
        'city' => 'string',
        'city_oid' => 'int',
        'county_oid' => 'int',
        'dont_collect_city' => 'bool',
        'dont_collect_postal_code' => 'bool',
        'postal_codes' => '\ultracart\v2\models\TaxPostalCode[]',
        'tax_rate' => 'float',
        'tax_rate_formatted' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'accounting_code' => null,
        'city' => null,
        'city_oid' => 'int32',
        'county_oid' => 'int32',
        'dont_collect_city' => null,
        'dont_collect_postal_code' => null,
        'postal_codes' => null,
        'tax_rate' => null,
        'tax_rate_formatted' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'accounting_code' => 'accounting_code',
        'city' => 'city',
        'city_oid' => 'city_oid',
        'county_oid' => 'county_oid',
        'dont_collect_city' => 'dont_collect_city',
        'dont_collect_postal_code' => 'dont_collect_postal_code',
        'postal_codes' => 'postal_codes',
        'tax_rate' => 'tax_rate',
        'tax_rate_formatted' => 'tax_rate_formatted'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'accounting_code' => 'setAccountingCode',
        'city' => 'setCity',
        'city_oid' => 'setCityOid',
        'county_oid' => 'setCountyOid',
        'dont_collect_city' => 'setDontCollectCity',
        'dont_collect_postal_code' => 'setDontCollectPostalCode',
        'postal_codes' => 'setPostalCodes',
        'tax_rate' => 'setTaxRate',
        'tax_rate_formatted' => 'setTaxRateFormatted'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'accounting_code' => 'getAccountingCode',
        'city' => 'getCity',
        'city_oid' => 'getCityOid',
        'county_oid' => 'getCountyOid',
        'dont_collect_city' => 'getDontCollectCity',
        'dont_collect_postal_code' => 'getDontCollectPostalCode',
        'postal_codes' => 'getPostalCodes',
        'tax_rate' => 'getTaxRate',
        'tax_rate_formatted' => 'getTaxRateFormatted'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['accounting_code'] = $data['accounting_code'] ?? null;
        $this->container['city'] = $data['city'] ?? null;
        $this->container['city_oid'] = $data['city_oid'] ?? null;
        $this->container['county_oid'] = $data['county_oid'] ?? null;
        $this->container['dont_collect_city'] = $data['dont_collect_city'] ?? null;
        $this->container['dont_collect_postal_code'] = $data['dont_collect_postal_code'] ?? null;
        $this->container['postal_codes'] = $data['postal_codes'] ?? null;
        $this->container['tax_rate'] = $data['tax_rate'] ?? null;
        $this->container['tax_rate_formatted'] = $data['tax_rate_formatted'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets accounting_code
     *
     * @return string|null
     */
    public function getAccountingCode()
    {
        return $this->container['accounting_code'];
    }

    /**
     * Sets accounting_code
     *
     * @param string|null $accounting_code Accounting code for programs such as QuickBooks
     *
     * @return self
     */
    public function setAccountingCode($accounting_code)
    {
        $this->container['accounting_code'] = $accounting_code;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string|null
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string|null $city City
     *
     * @return self
     */
    public function setCity($city)
    {
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets city_oid
     *
     * @return int|null
     */
    public function getCityOid()
    {
        return $this->container['city_oid'];
    }

    /**
     * Sets city_oid
     *
     * @param int|null $city_oid Tax record object identifier used internally by database
     *
     * @return self
     */
    public function setCityOid($city_oid)
    {
        $this->container['city_oid'] = $city_oid;

        return $this;
    }

    /**
     * Gets county_oid
     *
     * @return int|null
     */
    public function getCountyOid()
    {
        return $this->container['county_oid'];
    }

    /**
     * Sets county_oid
     *
     * @param int|null $county_oid Tax record object identifier used internally by database
     *
     * @return self
     */
    public function setCountyOid($county_oid)
    {
        $this->container['county_oid'] = $county_oid;

        return $this;
    }

    /**
     * Gets dont_collect_city
     *
     * @return bool|null
     */
    public function getDontCollectCity()
    {
        return $this->container['dont_collect_city'];
    }

    /**
     * Sets dont_collect_city
     *
     * @param bool|null $dont_collect_city Flag instructing engine to not collect city tax for this city
     *
     * @return self
     */
    public function setDontCollectCity($dont_collect_city)
    {
        $this->container['dont_collect_city'] = $dont_collect_city;

        return $this;
    }

    /**
     * Gets dont_collect_postal_code
     *
     * @return bool|null
     */
    public function getDontCollectPostalCode()
    {
        return $this->container['dont_collect_postal_code'];
    }

    /**
     * Sets dont_collect_postal_code
     *
     * @param bool|null $dont_collect_postal_code Flag instructing engine to not collect postal code tax for this city
     *
     * @return self
     */
    public function setDontCollectPostalCode($dont_collect_postal_code)
    {
        $this->container['dont_collect_postal_code'] = $dont_collect_postal_code;

        return $this;
    }

    /**
     * Gets postal_codes
     *
     * @return \ultracart\v2\models\TaxPostalCode[]|null
     */
    public function getPostalCodes()
    {
        return $this->container['postal_codes'];
    }

    /**
     * Sets postal_codes
     *
     * @param \ultracart\v2\models\TaxPostalCode[]|null $postal_codes Postal Codes within this city
     *
     * @return self
     */
    public function setPostalCodes($postal_codes)
    {
        $this->container['postal_codes'] = $postal_codes;

        return $this;
    }

    /**
     * Gets tax_rate
     *
     * @return float|null
     */
    public function getTaxRate()
    {
        return $this->container['tax_rate'];
    }

    /**
     * Sets tax_rate
     *
     * @param float|null $tax_rate Tax Rate
     *
     * @return self
     */
    public function setTaxRate($tax_rate)
    {
        $this->container['tax_rate'] = $tax_rate;

        return $this;
    }

    /**
     * Gets tax_rate_formatted
     *
     * @return string|null
     */
    public function getTaxRateFormatted()
    {
        return $this->container['tax_rate_formatted'];
    }

    /**
     * Sets tax_rate_formatted
     *
     * @param string|null $tax_rate_formatted Tax rate formatted
     *
     * @return self
     */
    public function setTaxRateFormatted($tax_rate_formatted)
    {
        $this->container['tax_rate_formatted'] = $tax_rate_formatted;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


