<?php
/**
 * CouponTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ultracart\v2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ultracart\v2;

/**
 * CouponTest Class Doc Comment
 *
 * @category    Class */
// * @description Coupon
/**
 * @package     ultracart\v2
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CouponTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Coupon"
     */
    public function testCoupon()
    {
    }

    /**
     * Test attribute "affiliate_oid"
     */
    public function testPropertyAffiliateOid()
    {
    }

    /**
     * Test attribute "amount_off_items"
     */
    public function testPropertyAmountOffItems()
    {
    }

    /**
     * Test attribute "amount_off_shipping"
     */
    public function testPropertyAmountOffShipping()
    {
    }

    /**
     * Test attribute "amount_off_shipping_with_items_purchase"
     */
    public function testPropertyAmountOffShippingWithItemsPurchase()
    {
    }

    /**
     * Test attribute "amount_off_subtotal"
     */
    public function testPropertyAmountOffSubtotal()
    {
    }

    /**
     * Test attribute "amount_off_subtotal_and_free_shipping"
     */
    public function testPropertyAmountOffSubtotalAndFreeShipping()
    {
    }

    /**
     * Test attribute "amount_off_subtotal_and_shipping"
     */
    public function testPropertyAmountOffSubtotalAndShipping()
    {
    }

    /**
     * Test attribute "amount_off_subtotal_with_block_purchase"
     */
    public function testPropertyAmountOffSubtotalWithBlockPurchase()
    {
    }

    /**
     * Test attribute "amount_off_subtotal_with_items_purchase"
     */
    public function testPropertyAmountOffSubtotalWithItemsPurchase()
    {
    }

    /**
     * Test attribute "can_be_used_with_other_coupons"
     */
    public function testPropertyCanBeUsedWithOtherCoupons()
    {
    }

    /**
     * Test attribute "coupon_oid"
     */
    public function testPropertyCouponOid()
    {
    }

    /**
     * Test attribute "coupon_type"
     */
    public function testPropertyCouponType()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "discount_item_with_item_purchase"
     */
    public function testPropertyDiscountItemWithItemPurchase()
    {
    }

    /**
     * Test attribute "discount_items"
     */
    public function testPropertyDiscountItems()
    {
    }

    /**
     * Test attribute "expiration_dts"
     */
    public function testPropertyExpirationDts()
    {
    }

    /**
     * Test attribute "free_item_and_shipping_with_subtotal"
     */
    public function testPropertyFreeItemAndShippingWithSubtotal()
    {
    }

    /**
     * Test attribute "free_item_with_item_purchase"
     */
    public function testPropertyFreeItemWithItemPurchase()
    {
    }

    /**
     * Test attribute "free_item_with_subtotal"
     */
    public function testPropertyFreeItemWithSubtotal()
    {
    }

    /**
     * Test attribute "free_items_with_item_purchase"
     */
    public function testPropertyFreeItemsWithItemPurchase()
    {
    }

    /**
     * Test attribute "free_items_with_mixmatch_purchase"
     */
    public function testPropertyFreeItemsWithMixmatchPurchase()
    {
    }

    /**
     * Test attribute "free_shipping"
     */
    public function testPropertyFreeShipping()
    {
    }

    /**
     * Test attribute "free_shipping_specific_items"
     */
    public function testPropertyFreeShippingSpecificItems()
    {
    }

    /**
     * Test attribute "free_shipping_with_items_purchase"
     */
    public function testPropertyFreeShippingWithItemsPurchase()
    {
    }

    /**
     * Test attribute "free_shipping_with_subtotal"
     */
    public function testPropertyFreeShippingWithSubtotal()
    {
    }

    /**
     * Test attribute "merchant_code"
     */
    public function testPropertyMerchantCode()
    {
    }

    /**
     * Test attribute "multiple_amounts_off_items"
     */
    public function testPropertyMultipleAmountsOffItems()
    {
    }

    /**
     * Test attribute "no_discount"
     */
    public function testPropertyNoDiscount()
    {
    }

    /**
     * Test attribute "percent_off_item_with_items_quantity_purchase"
     */
    public function testPropertyPercentOffItemWithItemsQuantityPurchase()
    {
    }

    /**
     * Test attribute "percent_off_items"
     */
    public function testPropertyPercentOffItems()
    {
    }

    /**
     * Test attribute "percent_off_items_and_free_shipping"
     */
    public function testPropertyPercentOffItemsAndFreeShipping()
    {
    }

    /**
     * Test attribute "percent_off_items_with_items_purchase"
     */
    public function testPropertyPercentOffItemsWithItemsPurchase()
    {
    }

    /**
     * Test attribute "percent_off_retail_price_items"
     */
    public function testPropertyPercentOffRetailPriceItems()
    {
    }

    /**
     * Test attribute "percent_off_shipping"
     */
    public function testPropertyPercentOffShipping()
    {
    }

    /**
     * Test attribute "percent_off_subtotal"
     */
    public function testPropertyPercentOffSubtotal()
    {
    }

    /**
     * Test attribute "percent_off_subtotal_and_free_shipping"
     */
    public function testPropertyPercentOffSubtotalAndFreeShipping()
    {
    }

    /**
     * Test attribute "percent_off_subtotal_limit"
     */
    public function testPropertyPercentOffSubtotalLimit()
    {
    }

    /**
     * Test attribute "percent_off_subtotal_with_items_purchase"
     */
    public function testPropertyPercentOffSubtotalWithItemsPurchase()
    {
    }

    /**
     * Test attribute "percent_off_subtotal_with_subtotal"
     */
    public function testPropertyPercentOffSubtotalWithSubtotal()
    {
    }

    /**
     * Test attribute "quickbooks_code"
     */
    public function testPropertyQuickbooksCode()
    {
    }

    /**
     * Test attribute "start_dts"
     */
    public function testPropertyStartDts()
    {
    }

    /**
     * Test attribute "tiered_amount_off_item"
     */
    public function testPropertyTieredAmountOffItem()
    {
    }

    /**
     * Test attribute "tiered_amount_off_subtotal"
     */
    public function testPropertyTieredAmountOffSubtotal()
    {
    }

    /**
     * Test attribute "tiered_percent_off_items"
     */
    public function testPropertyTieredPercentOffItems()
    {
    }

    /**
     * Test attribute "tiered_percent_off_shipping"
     */
    public function testPropertyTieredPercentOffShipping()
    {
    }

    /**
     * Test attribute "tiered_percent_off_subtotal"
     */
    public function testPropertyTieredPercentOffSubtotal()
    {
    }

    /**
     * Test attribute "usable_by"
     */
    public function testPropertyUsableBy()
    {
    }
}
